### ISSUE TITLE
[FEATURE] ALL Issues, 1.5

### ISSUE THREAD

**Issue by Klemci** [ElektroStudios/Easy-Link-File-Viewer#11]
**Interface enhancements :**

1 - ABOUT (fix)
2 - RAW + "view mode" buttons (hide)
3 - Recent files list, add option to disable (in a submenu), if never used by an user, usefull.

**Describe the solution you'd like**

A - ABOUT button is too near SAVE toolbar button, user will errorously push it instead, move it to the verry right of the title bar perhaps ?
B - Add option to not show RAW tab and the buttons to change view style = less cluttered.
C - Recent files is not usefull for everybody, an option to "freeze" list would be good.

GOOD LUCK

**Additional context**
![ALLIssues](https://github.com/ElektroStudios/Easy-Link-File-Viewer/assets/90113078/963026d2-39b4-4ad7-bd2b-576c1a500264)

**Comment by Klemci** [comment]
About recent files list, yes, it's of no use to me.

Option possible behavior:
When the mouse opens submenu, recent files are showed...
... if the first line (add separator for more visibility) is an option to switch ON/OFF the list functionnability like some apps have a line to flush recent files too (e.g: VBA-M VisualBoyAdvance).

Thanks, i'm not in a hurry and will be patient to see next release out.

![Presse-papier_03-05-2024_01](https://github.com/ElektroStudios/Easy-Link-File-Viewer/assets/90113078/a96e4ebe-659b-4175-8d5a-9eab939c5674)

**Comment by ElektroStudios** [comment]
I finally decided to add an option in the "Settings" menu. Please check [the new release](https://github.com/ElektroStudios/Easy-Link-File-Viewer/releases/tag/v1.6).

**Comment by Klemci** [comment]
Perfect

now it's a tool with a clean UI, and advanced options availables optionnaly.
