### ISSUE TITLE
Support new version of .lnk which targets Microsoft Store App

### ISSUE THREAD

**Issue by fuweichin** [ElektroStudios/Easy-Link-File-Viewer#5]
It seems a new version/format of .lnk comes out in Windows 10. With Windows' built-in file Properties dialog, I cannot modify key properties of .lnk file which targets Microsoft Store App.

I want to figure out full target information which is to be used in XLaunchpad to create a launch item.

To create that kind of .lnk, see [Create Desktop Shortcut for Store app in Windows 10](https://winaero.com/desktop-shortcut-store-app-windows-10/)

![traditional-lnk-and-store-app-lnk](https://user-images.githubusercontent.com/1687235/138666274-3b0e70c0-7bb9-4af7-86db-9aa0775a81d3.png)

**Comment by Hexaae** [comment]
Same here. Wanted to edit a game link file but it actually destroyed Microsoft Store games .lnk file :(

**Comment by Hexaae** [comment]
Found an alternative tool, perfectly working and able to add command line arguments for .lnk files created by XBox app (Microsoft Store games):
https://flint-inc.ru/eng/info/linkinfo.html

**Comment by ElektroStudios** [comment]
Hi. I am very sorry for the delay in offering a response, but I have had this project quite forgotten and abandoned.

Responding to your question, that kind of link from Microsoft Word is not a "new" link format, it is a link composed by [Item Identifiers and Identifier Lists](https://learn.microsoft.com/en-us/windows/win32/shell/links#item-identifiers-and-identifier-lists).

**Easy Link File Viewer** was aware of item identifiers for shell folders, but it was not working as expected for some kind of links with other item identifiers such as for example a link created by an MSI installer. 

The mentioned third party tool, [LinkEditor](https://flint-inc.ru/eng/info/linkinfo.html), it also does not work properly (it can't retrieve the program target) for those kind of link files from Windows Installer products, such as link files created by Microsoft Word or Nero Burning ROM MSI installers.

I've implemented experimental functionality in **Easy Link File Viewer** to try properly read/write those kind of links, please see change log of [release v1.6](https://github.com/ElektroStudios/Easy-Link-File-Viewer/releases/tag/v1.6).

If you have more questions feel free to continue asking in this thread. For now, I consider it completed.

And sorry again for the delay in my answers.

Sincerely,
Elektro.

**Comment by ElektroStudios** [comment]
> Same here. Wanted to edit a game link file but it actually destroyed Microsoft Store games .lnk file :(

Hi. Again I need to say: I am very sorry for the delay in offering a response, but I have had this project quite forgotten and abandoned.

And I feel sorry for the application to have corrupted your link file, but I've made updates applying consistent security changes providing various recent releases, ¡please give it a try for one last time!: https://github.com/ElektroStudios/Easy-Link-File-Viewer/releases

Sincerely, 
Elektro.
