### ISSUE TITLE
Save Icon - Toolbar

### ISSUE THREAD

**Issue by Klemci** [ElektroStudios/Easy-Link-File-Viewer#8]
If there was the SAVE icon in toolbar it would be quicker to edit shortcuts !

Thanks

**Comment by ElektroStudios** [comment]
Hi. I am very sorry for the delay in offering a response, but I have had this project quite forgotten and abandoned.

Responding to your question, this would be the the prototype:

![](https://i.imgur.com/xCZ9GTi.png)

Additionally, a new option to let the user show or hide that toolbar.

All this it will be implemented in the next release.

This may take me some time (from few days, to weeks) as there are several other Issues in this project that I also need to offer solutions to. Please be patient.

Sincerely,
Elektro.

**Comment by Klemci** [comment]
Perect, and thanks for all.

**Comment by ElektroStudios** [comment]
The fix has already been implemented in the new source code update. See [change log](https://github.com/ElektroStudios/Easy-Link-File-Viewer/blob/master/Docs/CHANGELOG.md).

Please wait for the new release to be published.

If you have more questions feel free to continue this debate. For now, I consider it completed.

And sorry again for the delay in my answers.
