### ISSUE TITLE
You are a hero, bro, Thanks a million

### ISSUE THREAD

**Issue by sobaee** [ElektroStudios/Easy-Link-File-Viewer#9]
You saved my day

You are the only one who come up with this great idea

All my respect 🙏🙏

There is an issue:

It can't replace the original .lnk file, you just need to "save as" for this to work.

Thanks a lot

**Comment by ElektroStudios** [comment]
Hi!. I am very sorry for the delay in offering a response, but I have had this project quite forgotten and abandoned.

Responding to your question, I would need more information to reproduce the problem that you were experiencing:

 - Were you using **Easy Link File Viewer** with administrator rights?.

 - Do you remember what were the file attributes of the .lnk file that you could not replace using the "Save" menu command?.

In any case, In any case, I'll keep this issue on the list of things to review in depth; I will perform different tests to try to save a .lnk file and will provide a solution for cases that are not successful. I hope that solves your problem in the end.

The changes made to satisfy those tests will be implemented in the next release.

This may take me some time (from few days, to weeks) as there are several other Issues in this project that I also need to offer solutions to. Please be patient.

Sincerely,
Electro.

**Comment by ElektroStudios** [comment]
Some workarounds have already been implemented in the new source code update to properly handle read-only link files when saving changes to the file, and also to handle failed saves due insufficient user permissions. See [change log](https://github.com/ElektroStudios/Easy-Link-File-Viewer/blob/master/Docs/CHANGELOG.md) of v1.5.

Please wait for the new release to be published with all these changes applied.

If you have more questions feel free to continue this debate. For now, I consider it completed.

And sorry again for the delay in my answers.
